version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"  # MQTT
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf